# Generated by Django 5.0.1 on 2024-01-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FrequencyRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("min_frequency", models.FloatField()),
                ("max_frequency", models.FloatField()),
            ],
        ),
    ]
