# Generated by Django 5.0.1 on 2024-01-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frequencyrange",
            name="max_frequency",
        ),
        migrations.RemoveField(
            model_name="frequencyrange",
            name="min_frequency",
        ),
        migrations.AddField(
            model_name="frequencyrange",
            name="key",
            field=models.CharField(default="C", max_length=2),
        ),
    ]
